---
# handlers file for nginx
- name: nginx systemd
  systemd: 
    name: nginx
    enebled: yes
    state: started

- name: nginx restart
  service:
    name: nginx
    state: restarted
  when:
    services_state.ansible_facts.services['nginx.service'].state == 'running'
  ignore_errors: yes