---
# tasks file for grafana
#sudo apt-get install -y adduser libfontconfig1 musl
#wget https://dl.grafana.com/oss/release/grafana_10.2.0_amd64.deb
#sudo dpkg -i grafana_10.2.0_amd64.deb


- name: Install a .deb package grafana 
  ansible.builtin.apt:
    deb: https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_amd64.deb

#sudo apt-get install -y adduser libfontconfig1 musl
#wget https://dl.grafana.com/enterprise/release/grafana-enterprise_10.2.0_amd64.deb
#sudo dpkg -i grafana-enterprise_10.2.0_amd64.deb

#sudo systemctl daemon-reload
#sudo systemctl start grafana-server
#sudo systemctl status grafana-server

- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: wait for service up
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

#- name: change admin password for grafana gui
#  shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
#  register: __command_admin
#  changed_when: __command_admin.rc !=0
- name: clean
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - grafana_{{ grafana_version }}

