---
# tasks file for blackbox
- name: Create directories for Blackbox Exporter
  file:
    path: /etc/blackbox
    state: directory
    owner: alertmanager
    group: alertmanager

- name: Create Blackbox Exporter user
  user:
    name: blackbox
    append: true
    shell: /bin/sbin/nologin
    system: true
    create_home: false

- name: Create directories for Blackbox Exporter
  file:
    path: /tmp/blackbox_exporter
    state: directory
    owner: blackbox
    group: blackbox

- name: download and unzip Blackbox Exporter if not exist
  unarchive:
    src: https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_version }}/blackbox_exporter-{{ blackbox_version }}.linux-amd64.tar.gz
    dest: /tmp/blackbox_exporter
    creates: /tmp/blackbox_exporter/blackbox_exporter-{{ blackbox_version }}.linux-amd64
    remote_src: yes

- name: Move the binary to the final destination blackbox_exporter
  copy:
    src: /tmp/blackbox_exporter/blackbox_exporter-{{ blackbox_version }}.linux-amd64/blackbox_exporter
    dest: /usr/local/bin
    remote_src: yes
    mode: preserve
    owner: blackbox
    group: blackbox

- name: Create unit blackbox service 
  copy:
    src: blackbox_exporter.service
    dest: /etc/systemd/system/
  notify:
    - systemd reload

- name: Copy blackbox_exporter.service to /etc/blackbox
  copy:
    src: blackbox.yml
    dest: /etc/blackbox/blackbox.yml
    owner: blackbox
    group: blackbox
  notify: blackbox reload

- name: Start blackbox_exporter.service
  systemd:
    name: blackbox_exporter
    state: started
    enabled: yes

- name: clean
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - '/tmp/blackbox_exporter'