---
- name: systemd reload
  systemd:
    daemon_reload: yes

- name: reload_daemon_and_restart_node_exporter
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes

