---
kube_servers:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: user
    ansible_ssh_private_key_file: ../dpl.key
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  hosts:
    server01:
      ansible_host: master.skfact.local
      ansible_ssh_host: 158.160.116.5
    server02:
      ansible_host: worker01.skfact.local
      ansible_ssh_host: 158.160.123.179
  
  children:
    master:
      hosts:
        server01:
    worker:
      hosts:
        server02:

srv_servers:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ../dpl.key
    ansible_user: user
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    virtual_domain: 158.160.118.237.sslip.io
    
  hosts:
    server03:
      ansible_host: srv.skfact.local
      ansible_ssh_host: 158.160.118.237
      
      